#!/bin/bash

ppa="bit-team/stable"
pkgs="backintime-qt4"
devpkgs="python-dbus python3-dbus python3-dbus.mainloop.qt python3.7-dev"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(_ppacheck ${ppa}) == "n" ] ; then
		echo TRUE
	else	
		echo FALSE 
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(_ppacheck ${ppa}) == "y" ] ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else
	_install ${devpkgs}
	_install ${pkgs}
	
	fi

	cp /usr/share/applications/gimp.desktop $(_desktop)/gimp.desktop
	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}

	rm -f $(_desktop)/gimp.desktop

fi
