#!/bin/bash

pkgs="clamtk"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "n" ] ; then
		echo FALSE
	else
		echo TRUE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then
	_install ${pkgs}
	
	echo "GUIの更新確認は不要なので無効化します。"
	mkdir "${HOME}/.clamtk"

echo "Recursive=1
GUICheck=0
ScanHidden=1" > "${HOME}/.clamtk/prefs"
	
	echo "シグネチャ（ウィルスの手配書）の更新を行います。"
	sudo freshclam
	
	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}



fi
