#!/bin/bash

ppa="dummy"
aptpkgs="devede"
debpkgs="python3-devedeng"



datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then

	if [ $(_check ${aptpkgs}) == "y" ]  &&  [ $(_check ${debpkgs}) == "n" ]   ; then
		echo TRUE
	else
		echo FALSE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	if [ $(_check ${aptpkgs}) == "n" ]  &&  [ $(_check ${debpkgs}) == "y" ]   ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else
	
	_install ${aptpkgs}
	
	fi

	
# Purge
elif [ "$1" == "-p" ] ; then

	_purge ${aptpkgs}



fi
