#!/bin/bash

pkgs="gimp "
ppa="otto-kesselgulasch/gimp"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(_ppacheck ${ppa}) == "n" ] ; then
		echo TRUE
	else	
		echo FALSE 
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(_ppacheck ${ppa}) == "y" ] ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else

	_install ${pkgs}
	
	fi

	cp /usr/share/applications/gimp.desktop $(_desktop)/gimp.desktop
	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}

	rm -f $(_desktop)/gimp.desktop

fi
