#!/bin/bash

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

ppa="dummy"
pkgs="lightworks"


# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ]  &&  [ $(_ppacheck ${ppa}) == "n" ] ; then
		echo TRUE
	else	
		echo FALSE 
	fi
	
# Install
elif [ "$1" == "-i" ] ; then
	echo "Lightworksをダウンロードしています。"
	cd /tmp
	deb="Lightworks-14.6.0.0-Beta-117868.deb"
	
	_log "${deb}"

	if wget -c  https://downloads.lwks.com/${deb} ; then
		_log "Lightworks-14.6.0.0-Beta-117868.debのダウンロードに成功しました。"
	else
		_err "Lightworks-14.6.0.0-Beta-117868.debのダウンロードに失敗しました。"
	
	fi
	
	if sudo dpkg -i ${deb}  ; then
		_log "Lightworks-14.6.0.0-Beta-117868.debのインストールに成功しました。"
	else
		sudo apt install --fix-broken
		_err "Lightworks-14.6.0.0-Beta-117868.debのインストールに失敗しました。"

	fi

	_log "一時ファイルを除去しています..."
	rm -f ${deb}

# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}

fi
