#!/bin/bash

ppa="dummy"
aptpkgs="ostorybook"


datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check

if [ "$1" == "-c" ] ; then
	if [ $(_check ${aptpkgs}) == "y" ]  ; then
		echo TRUE
	else
		echo FALSE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	echo "OstoryBookをダウンロードしています。"
	cd /tmp

	deb="oStorybook-5.04.05d.deb"
	

	if wget -c   http://download.tuxfamily.org/ostorybook/5.04.05d/${deb} ; then
		_log "$debのダウンロードに成功しました。"
	else
		_err "$debのダウンロードに失敗しました。"
	
	fi
		
	
	if sudo dpkg -i ${deb}  ; then
		_log "$debインストールに成功しました。"
	else
		sudo apt update --fix-missing
		if sudo apt install --fix-broken ; then
			_log "$pkgsインストールに成功しました。"
		else
			_err "$pkgsのインストールに失敗しました。"

		fi

	fi

	_log "一時ファイルを除去しています..."

	rm -f ${deb}


	
# Purge
elif [ "$1" == "-p" ] ; then

	_purge ${aptpkgs}


fi

