#!/bin/bash

ppa="dummy"
pkgs="synfig synfigstudio"

datadir=$(cd $(dirname "$0") && pwd)
instdir="/home/$(whoami)"

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ -e $instdir/synfig.git/_debug/build/bin/synfigstudio ] ; then
		echo TRUE
	else
		echo FALSE
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	if [ -d  $instdir/synfig.git  ] ; then
		rm -rf $instdir/synfig.git
	fi

_installsynfigstudio()
{

	git clone https://github.com/synfig/synfig.git $instdir/synfig.git
	cd $instdir/synfig.git
	bash   $instdir/synfig.git/1-setup-linux-native.sh
	bash   $instdir/synfig.git/2-build-debug.sh
	
# DeskTopの追加
echo "[Desktop Entry]
Name=Synfig Studio(GitMaster)
GenericName=2D vector animation studio
GenericName[ar]=استوديو الرسوم المتجهية المتحركة ثنائيى الابعاد 2d
GenericName[bs]=2D vektorski studio za animaciju
GenericName[ca]=Estudi d'animació vectorial 2D
GenericName[ca@valencia]=Estudi d'animació vectorial 2D
GenericName[cs]=2D vektorové animační studio
GenericName[da]=2D vektor animationsstudie
GenericName[de]=2D-Vektor-Animationsstudio
GenericName[en_GB]=2D vector animation studio
GenericName[es]=Estudio de animación vectorial 2D
GenericName[eu]=2D animazio bektorialaren estudioa
GenericName[eu_ES]=2D animazio bektorialaren estudioa
GenericName[fa_IR]=استودیوی پویانمایی وکتور 2بعدی
GenericName[fr]=Studio d'animation vectorielle 2D
GenericName[hu]=2D vektoros animációs stúdió
GenericName[it]=Studio animazione vettoriale 2D
GenericName[ja_JP]=２次元ベクター・アニメーション・スタジオ
GenericName[lt]=2D vektorinės animacijos studija
GenericName[nl]=2D vectoranimatiestudio
GenericName[pl_PL]=Studio wektorowej animacji 2D
GenericName[pt]=Estúdio de animação vetorial 2D
GenericName[pt_BR]=Estúdio de animação vetorial 2D
GenericName[ru]=Студия двухмерной векторной анимации
GenericName[sk_SK]=2D vektorové animačné štúdio
GenericName[sl]=Studio za vektorsko 2D animacijo
GenericName[sr_RS]=Творац 2-димензионалних покретних слика
GenericName[sv_SE]=2D-vektoranimationsstudio
GenericName[tr]=2 boyutlu vektör animasyon studio
GenericName[zh_CN]=2D 矢量动画工作室
GenericName[zh_TW]=2D 向量動畫工作室
Comment=Create and edit 2D animations and compositions
Comment[ar]=اصنع وعدل رسوم متحركة وتراكيب ثنائية الابعاد 2d
Comment[bs]=Kreiraj i uređuj 2D animacije i kompozicije
Comment[ca@valencia]=Crea i edita composicions i animacions en 2D
Comment[cs]=Vytvoření a úprava 2D animace a kompozice
Comment[da]=Skab og rediger 2D animationer og opstillinger
Comment[de]=Erstellen und bearbeiten Sie 2D-Animationen und -Kompositionen
Comment[es]=Crea y edita composiciones y animaciones 2D
Comment[eu]=Sortu eta editatu 2D animazioak eta konposizioak
Comment[fr]=Créer et éditer des animations et compositions 2D
Comment[it]=Crea ed edita animazioni e composizioni 2D
Comment[nl]=Maak en bewerk 2D-animaties en composities
Comment[pl_PL]=Tworzenie i edycja animacji i kompozycji  2D
Comment[pt]=Criar e editar animações 2D e composições
Comment[pt_BR]=Criar e editar animações 2D e composições
Comment[ru]=Создание двухмерной анимации
Comment[sk_SK]=Vytvárajte a meňte 2D animácie a kompozície
Comment[sl]=Ustvari in urejaj 2D animacijo in sestavke
Comment[sr_RS]=Ствaрајте и уређујте 2-димензионалне покретне слике и композиције
Comment[sv_SE]=Skapa och redigera 2D-animationer och -kompositioner
Comment[tr]=2B animasyonlar ve kompozisyonlar oluşturun ve düzenleyin
Comment[zh_CN]=创建、编辑 2D 动画或静态图像
Comment[zh_TW]=建立和編輯 2D動畫及創作
Exec=$instdir/synfig.git/_debug/build/bin/synfigstudio %F
Terminal=false
Type=Application
Icon=$instdir/synfig.git/_debug/build/share/icons/hicolor/scalable/apps/org.synfig.SynfigStudio.svg
Categories=GTK;Graphics;2DGraphics;VectorGraphics;
StartupNotify=true
MimeType=application/x-sif;
Keywords=2D;Vector;Animation;Cartoon;Anime;FX;Draw;Flash;ToonBoom;Moho;" | sudo tee -a  /usr/share/applications/synfigstudiogit.desktop

}


	if [ $(_check ${pkgs}) == "y" ]  ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else
		read -n1 -p "ホームディレクトリに開発版をインストールします。よろしいですか? (y/N): " yn
		if [[ $yn = [yY] ]]; then
			echo "インストールを継続します。"

			_installsynfigstudio | grep -e Error -e Fatal  -e NOTE  >> /tmp/mm_pkginst.log

		else
			echo "終了します。"
			exit
		fi

	fi
		
	if [ -e $instdir/synfig.git/_debug/build/bin/synfigstudio ] ; then
		_log "synfigstudio(GitMaster)のインストールに成功しました。"
	else
		_err "synfigstudio(GitMaster)のインストールに失敗しました。フォルダが残ったかもしれませせん。"
	fi


	
# Purge
elif [ "$1" == "-p" ] ; then


_uninstallsynfigstudio()
{
	sudo rm -rf  $instdir/synfig.git/
	sudo rm -f  /usr/share/applications/synfigstudiogit.desktop
	rm -rf  $instdir/.config/synfig
	rm -rf  $instdir/.synfig
	
	echo 1

}
       
    
	if [ $(_uninstallsynfigstudio) ] ; then
		_log "SynfigStudio(GitMaster)のアンインストールに成功しました。"
	else
		_err "SynfigStudio(GitMaster)のアンインストールに失敗したかフォルダが残ったかもしれませせん。"
	fi


fi
