#!/bin/bash

ppa="dummy"
pkgs="synfig synfigstudio"

datadir=$(cd $(dirname "$0") && pwd)

. ${datadir}/00common.fnc

# Check
if [ "$1" == "-c" ] ; then
	if [ $(_check ${pkgs}) == "y" ]  &&   [ ! -e /opt/synfig/bin/synfigstudio ] ; then
		echo TRUE
	else	
		echo FALSE 
	fi
	
# Install
elif [ "$1" == "-i" ] ; then

	if  [ -e /opt/synfig/bin/synfigstudio ] ; then
		_err "既に他のバージョンが存在します。他のバージョンのアンインストールが必要です。"
	else

	_install ${pkgs}
	
	fi
	
	if [ $(_check ${pkgs}) == "y" ]  ; then
		_log "synfigstudioのインストールに成功しました。"
	else
		_err "synfigstudioのインストールに失敗しました。フォルダが残ったかもしれませせん。"
	fi
	
	

	
# Purge
elif [ "$1" == "-p" ] ; then
	_purge ${pkgs}

	if [ $(_check ${pkgs}) == "n" ]  ; then
		_log "synfigstudioのアンインストールに成功しました。"
	else
		_err "synfigstudioのアンインストールに失敗しました。フォルダが残ったかもしれませせん。"
	fi


fi
